version: "2"

services:
  angular:
    build: angular-client
    ports:
      - "4200:4200"

  express:
    build: express-server
    ports:
      - "3000:3000"

  database:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=db-location.crqxs6wlv6lh.us-east-2.rds.amazonaws.com
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=postgres

    ports:
      - "5432:5432"

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123"
    ports:
      - "16543:80"
    depends_on:
      - database
